In [1]:
import duckdb

ModuleNotFoundError: No module named 'duckdb'

In [2]:
import sys

In [3]:
print(sys.executable)

d:\Rebecca\ANACONDA\python.exe

In [4]:
import duckdb

ModuleNotFoundError: No module named 'duckdb'

In [5]:
import sys
print(sys.executable)

d:\Rebecca\ANACONDA\python.exe

In [6]:
import sys 
!{sys.executable} -m pip install duckdb

Requirement already satisfied: duckdb in d:\rebecca\anaconda\lib\site-packages (1.4.4)

In [7]:
import duckdb

In [8]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

NameError: name 'duckdb' is not defined

In [5]:
import duckdb
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [25]:
import pandas as pd
from datetime import datetime
arquivo = 'z0019_2.csv'
data_ingestão = datetime.now()
df = pd.read_csv(f'..\landing\{arquivo}', sep = ';')
df['nome_arquivo'] = arquivo
df['data_ingestão'] = data_ingestão
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestão
0   1004    SERRA  BT50    100    200  z0019_2.csv 2026-02-17 08:09:59.307653
1   1005  MACHADO  BT50    100    100  z0019_2.csv 2026-02-17 08:09:59.307653
2   1003    PREGO  BT10    100     60  z0019_2.csv 2026-02-17 08:09:59.307653

In [28]:
con.execute("""
Create table if not exists bronze_produtos(
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestão TIMESTAMP
            )
""")

In [29]:
con.execute("insert into bronze_produtos select * from df")

In [33]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head()

  NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestão
0  1001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-02-17 07:01:04.013625
1  1002   MARTELO  BT50   100  1500  z0019_1.csv 2026-02-17 07:01:04.013625
2  1003     PREGO  BT10   100    50  z0019_1.csv 2026-02-17 07:01:04.013625
3  1004     SERRA  BT50   100   200  z0019_2.csv 2026-02-17 08:09:59.307653
4  1005   MACHADO  BT50   100   100  z0019_2.csv 2026-02-17 08:09:59.307653

In [31]:
con.execute("ALTER table bronze_produtos RENAME to bronze_z0019")

In [34]:
con.close()