In [1]:
import duckdb

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [ ]:
df = con.execute ("select * from produtos").fetchdf()
df.head(10)

     id nm_produto id_categoria  id_fornecedor  vl_preço
0  1005    MACHADO         BT50            100     100.0
1  1001   PARAFUSO         BT10            100     100.0
2  1003      PREGO         BT10            100      60.0
3  1002    MARTELO         BT50            100    1500.0
4  1004      SERRA         BT50            100     200.0

In [6]:
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)

     id nm_produto  vl_preço
0  1005    MACHADO     100.0
1  1001   PARAFUSO     100.0
2  1003      PREGO      60.0
3  1002    MARTELO    1500.0
4  1004      SERRA     200.0

In [7]:
con.execute("""
    Create table if not exists dim_produtos(
    id_produto BIGINT,
    nm_produto TEXT,
    vl_preço FLOAT
    )
""")

In [9]:
con.execute("insert into dim_produtos SELECT * FROM df2")

In [10]:
df_dim = con.execute ("select * from dim_produtos").fetchdf()
df_dim.head(10)

   id_produto nm_produto  vl_preço
0        1005    MACHADO     100.0
1        1001   PARAFUSO     100.0
2        1003      PREGO      60.0
3        1002    MARTELO    1500.0
4        1004      SERRA     200.0